# Generated by Django 5.0.9 on 2024-11-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_celular_alter_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': '1.1- Cadastro'},
        ),
    ]
