# Generated by Django 5.0.9 on 2024-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(blank=True, choices=[('Em Andamento', 'Em Andamento'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Cancelado', 'Cancelado')], default='Em Andamento', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
